server:
  port: 10463
spring:
  application:
    name: nacos-config
nacos:
  config:
    server-addr: localhost:8848
    username: nacos
    password: nacos
  discovery:
    server-addr: localhost:8848
    username: nacos
    password: nacos
    auto-register: true
